apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
spec:
  params:
    - name: endpoint
      description: minio endpoint
      default: 192.168.88.36:31195
    - name: username
      description: minio key
      default: admin
    - name: password
      description: minio secret
      default: Esri@123
    - name: bucket
      description: minio bucket
      default: src
    - name: filename
      description: zip filename
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: pathToDockerFile
      description: The path to the dockerfile to build (relative to the context)
      default: src/Dockerfile
    - name: imageUrl
      description: Url of image repository
    - name: imageTag
      description: Tag to apply to the built image
      default: latest
  tasks:
    - name: fetch-build-push
      taskRef:
        name: fetch-build-push
      params:
        - name: endpoint
          value: "$(params.endpoint)"
        - name: username
          value: "$(params.username)"
        - name: password
          value: "$(params.password)"
        - name: bucket
          value: "$(params.bucket)"
        - name: filename
          value: "$(params.filename)"
        - name: filename
          value: "$(params.filename)"
        - name: pathToContext
          value: "$(params.pathToContext)"
        - name: imageUrl
          value: "$(params.imageUrl)"
        - name: imageTag
          value: "$(params.imageTag)"
    - name: deploy-to-cluster
      taskRef:
        name: deploy-using-kubectl
      runAfter:
        - fetch-build-push
      params:
        - name: pathToYamlFile
          value: "$(params.pathToYamlFile)"
        - name: imageUrl
          value: "$(params.imageUrl)"
        - name: imageTag
          value: "$(params.imageTag)"
