apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-deploy
  namespace: knative-app
spec:
  params:
    - name: endpoint
      description: minio endpoint
      default: 192.168.88.36:31195
    - name: username
      description: minio key
      default: admin
    - name: password
      description: minio secret
      default: Esri@123
    - name: bucket
      description: minio bucket
      default: src
    - name: filename
      description: zip filename
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: pathToDockerFile
      description: The path to the dockerfile to build (relative to the context)
      default: Dockerfile
    - name: imageUrl
      description: Url of image repository
    - name: imageTag
      description: Tag to apply to the built image
      default: latest
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the workspace
      default: service.yaml
  steps:
    - name: fetch-and-unzip
      image: 192.168.199.205:80/knative-app/fetch:v1
      args:
        [
          "-endpoint",
          "$(params.endpoint)",
          "-username",
          "$(params.username)",
          "-password",
          "$(params.password)",
          "-bucket",
          "$(params.bucket)",
          "-filename",
          "$(params.filename)",
          "-dest",
          "$(params.pathToContext)",
        ]
    - name: build-and-push
      image: registry.cn-hangzhou.aliyuncs.com/zhangfuxing/kaniko-project-executor:latest
      command:
        - /kaniko/executor
      args:
        [
          "--dockerfile=$(params.pathToDockerFile)",
          "--destination=$(params.imageUrl):$(params.imageTag)",
          "--context=/workspace/$(params.pathToContext)",
        ]
      env:
        - name: DOCKER_CONFIG
          value: /builder/home/.docker
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;__IMAGE__;$(params.imageUrl):$(params.imageTag);g"
        - "/workspace/$(params.pathToYamlFile)"
    - name: run-kubectl
      image: 192.168.199.205:80/knative-app/kubectl:0.5.0
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "/workspace/$(params.pathToYamlFile)"
