apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-using-kubectl
  namespace: knative-app
spec:
  params:
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the workspace
      default: service.yaml
    - name: imageUrl
      description: Url of image repository
    - name: imageTag
      description: Tag of the images to be used.
      default: latest
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;__IMAGE__;$(params.imageUrl):$(params.imageTag);g"
        - "/workspace/$(params.pathToYamlFile)"
    - name: run-kubectl
      image: registry.cn-hangzhou.aliyuncs.com/knative-sample/kubectl:v0.5.0
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "/workspace/$(params.pathToYamlFile)"
