apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-build-push2
  namespace: knative-app
spec:
  params:
    - name: endpoint
      description: minio endpoint
      default: 192.168.88.36:31195
    - name: username
      description: minio key
      default: admin
    - name: password
      description: minio secret
      default: Esri@123
    - name: bucket
      description: minio bucket
      default: src
    - name: filename
      description: zip filename
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: pathToDockerFile
      description: The path to the dockerfile to build (relative to the context)
      default: Dockerfile
    - name: imageUrl
      description: Url of image repository
    - name: imageTag
      description: Tag to apply to the built image
      default: latest
  steps:
    - name: build-and-push
      image: registry.cn-hangzhou.aliyuncs.com/zhangfuxing/kaniko-project-executor:latest
      command:
        - /kaniko/executor
      args:
        [
          "--dockerfile=$(params.pathToDockerFile)",
          "--destination=$(params.imageUrl):$(params.imageTag)",
          "--context=s3://$(params.bucket)/$(params.filename)",
        ]
      env:
        - name: DOCKER_CONFIG
          value: /builder/home/.docker
        - name: AWS_ACCESS_KEY_ID
          value: "$(params.username)"
        - name: AWS_SECRET_ACCESS_KEY
          value: "$(params.password)"
        - name: AWS_REGION
          value: us-east-1
        - name: S3_ENDPOINT
          value: "$(params.endpoint)"
        - name: S3_FORCE_PATH_STYLE
          value: "true"
