apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tekton-kn-sample
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  params:
    - name: pathToContext
      value: "src"
    - name: pathToYamlFile
      value: "src/helloworld-go.yaml"
    - name: imageUrl
      value: "192.168.199.205:80/knative-app/tekton-knative-helloworld"
    - name: imageTag
      value: "latest"
  serviceAccountName: pipeline-account
