apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: deploy-using-kubectl-run-hellogo
  namespace: knative-app
spec:
  taskRef:
    name: deploy-using-kubectl
  serviceAccountName: pipeline-account
  params:
    - name: pathToContext
      value: "src"
    - name: imageUrl
      value: "192.168.199.205:80/knative-app/tekton-knative-helloworld"
    - name: imageTag
      value: "latest"